apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:oeNq423e2iVfGwDMC3tDHBodjp5XMMXnoSTBRdL5Xqz860JrcqA//3pfO7gamK8LC/QylK06t9hpG8odTQ4/JevXkB6SEhNqyhWee/ci9uiY/cg2nYdf31kYd5Au3mpltm2TK+ERWTnMX45VC6ab5nSpYUnvYwzmk3Grby4pDkdmYQRenSXJsr1/qCTzWdZrgT5+TOqIl4sTmvK961RlS7tBAlH8qkgpd0o/d6wX/q/Xs/z5NXfikz7fThaVw7cV0nhiIpIQqOky8nVwr/dwOIn2RMfu9lYRErWokui4yY0QjuNGc4RyK1oPb2rExmA6JbxY2MS35bpBotIdz3DBG+IfZllPqH/eCUgD3p7jKYTzI9i4EObHyQJz93dNUSuA,iv:HPn02yewf4qhX4FAw1ehr4cqGl3dyDrcsbF8vmMm9ow=,tag:E/W846xEKzo3Q2gWRIcs4A==,type:str]
    identity.pub: ENC[AES256_GCM,data:0+cXx1iYBY7Rgnn2AOqsMQKet7+51hjGBsLkezCPSzy42Mymr6QokMs22txWjlkG21fYoKZkQ5XGAmTxg/Nk6UeCekxU9FaIqSovr0R5GSD8L7KL99jU660VGL6R/YngwpbEE0aRev97AxopSHwOonU2/l7KwPc4ffO/Bopy9v1xnnK4GyE83yWdTLw1hyU47qkO8sUedRZMg+0o3MrAmz4kfsubrBGUm7qAe2PJmarInV2WrVDwPI7D/MFkFW6QW57ll3Xq8h7/sqPCTw==,iv:KxoywRc2Ws2X+NPtaSZY9tlFPGHX7pcJORH4r4MvKWE=,tag:ALKTpHQfvsqHO7l2YJwAHw==,type:str]
    known_hosts: ENC[AES256_GCM,data:wH1U4gReipFY8iZzZGOzCeq1PRp5/MqUKPvV4+PE6AjPVHyD9uifFy8+T7LXrinXmjCQ1zKfaozYJMVPl29H1qDVyw2+TdqqpUzF2rxHg+ynz7uA7A+uEmi5x/h9drtCP4L7+7aULqFB8vnvsHOMDIvCJ4tlNOFZRF4SUxRqFT9CEAOyT1+1m6YY7dX6bZkyaruAk+vP/Yv1yimLIsMzpkFjFCnnxoCkaoA9,iv:1iyLylRTcj7u+dy5hm8HbkRKC5ZWBAtSvy8Z4t/rYbA=,tag:CqNguECLVoHpZcceU+ehew==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveHFiTHN3aXRIdnNScUlP
            M0s4MkJCS2hiZWxGaWlpMVVManp0VWZSQ0E0Ck9WdWYrQmMwakQ2MGd6c3JSY3Fl
            NC9DRTZCbTNVc2JqTnF0cDVHLzY3S2sKLS0tIHFDVjJVMU1xOHFsZmZmVUUwb1JB
            SE1HSUtqZ2NacmE1aEpMU0lVc3hiZmcKi8/b6TMcWn2BKvSkdUVLVxhV1ZjEdP4c
            aAol+PhXXFLRcDouLfcghxOaibLqr5EaP7mJBoPj0CyIPmNMaEyGCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9tnad5563zuz9mjnsypq2h93jhc03lmpehxat60wpczg0927prq7daz46
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-19T21:27:12Z"
    mac: ENC[AES256_GCM,data:S7imTOXHN2jeq91hoKmzmgKfThSIsDtDWOtcQD0CybiUzCkQn+EHJ/JV0hfSPQl1Y00/+fjqSNUrC2xjQSRkzvX53IXle19pQXnxsHLiz8CCkucR89l2zXo72MNnCyZZLiSSwf138PKfxezeXHhYliK5n3ca50a4E/h4mShUNSw=,iv:W2JtkEUkQA4XYbYY/zopuDapI+/uuu0y+r8gaYGiTpo=,tag:Rw2ymsGnylgxm+zrLLpLTQ==,type:str]
    shamir_threshold: 3
    version: 3.13.1
