apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:XIvhO+sTOuWMzzbay3i6CO/0JatNENTYYbSvC03JEnMuUXTRIR74FHtfrmTT2Bgj/RWCSLKdYMBe4Qbl//JjhPzvt+m4HRe+4YXVM7a4756IHAr7XCDN77NY8GaO+ul4nn03DENJJ4FoxWfxP1FvxuBNI6cbphD2D5zjkZWR9ELYacx/tNR53PKRtGHJXH7qfswsMJLEhwblsGHFFE+YH+1uZ3uoLKsvZM6g/k6xnRCpGQeJXbsazbM1fT4ON9IBTPtkw/aEDgOEtQ+zU9TIOoi4OLsrK6w+CMqVyaQSQ3gD4FzGohVYt+hiLSGZo8ZIposn0ODai8vgW/xiIq1Yrs5FCZ3ntvb19UOcULWSAjecEtRX27Cj0W8HwVlZo5a5,iv:kUQ+gTVn2s/WkBU1ViFVllRrXYYnJlaDRqf4V36yQvI=,tag:33dlwnR0fqZRZoprJATYxQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:hpVZjApdJA/DNwWedRaggw5UYAWUHo4i8yBZkwp+Fkts3sPTlRMSXO35RdVQEea8Z2jo+IB4vzpuXMxxbtvViB41g9GpPl07rsopgey3tzM6cho0kVSMPrK/zVqs0EkYYiVyAukqjRWIvLA96e0YgbiqJ6G1cErUntKRXvg867s27FRbeh2r3fQPdUi/t7vhR7EktJk5fs6uGgg0ZkFv6EVnSRXa3msDnIHWn2SwMFGdRaCIuGOKDfPl9QOdAWliOYvTG6o0dXdA2ALr1Q==,iv:Lz4TuF/2l8HWWgdfZwr6gUW7dMx+4EWaEy9lzhnTEp4=,tag:3Wtpa7Iassmk/lBbqefueA==,type:str]
    known_hosts: ENC[AES256_GCM,data:V/UK6pOI9SwcQwKSCQzdhpETn4ZC2Snhus7yAkGlFe6MgYS32zH9x8lHypvKPZEyA66oliyni9hVueQo012gbuevawhMlweoEuuxogckKb2F2CTwylzIXGbFzj5ed7+BnlRTdvoXf9m6li8VPMMq3t1xZ6HJbIFG60cLFSFv+pVxzfpOXyVN55dEYy3e3rjHAghVrY/eY3yc0YH0tZuNJN0/MGDgMXnJRXXQ,iv:6nsy0KHiokwyhhwgyCyk6VeMvSQ7jDxbYRFrAEos5BA=,tag:2AqaQ2A5aBXJbG/k250Ewg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNFZpeUVEcHpnV3lnenpY
            QlBGUC9HWmwxQk01cUtaUEdycTJHNU9UTms4ClhWSmtWQzNoZ1N1RDNxVDVtYWdz
            WitDeFVBZ2NTVldYSFBUemg3R1lySG8KLS0tIHRPZkFrMTBicndWcHpyQmlLWGtP
            QnR5Um0xYnFMRExkNnFsbkhwcnJURncKnIIpd7wqbLUwgAREyw+ZGbxT6W67uLnA
            9vnZQ9RP8g+QoCU2UyT5FNz/ra7X1XgSv4znpI4j2+kzIqh2y8kTsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9tnad5563zuz9mjnsypq2h93jhc03lmpehxat60wpczg0927prq7daz46
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-21T07:11:23Z"
    mac: ENC[AES256_GCM,data:txlupYQzabBqA1E5yphZOq1zztpKbNqEnX85AcAD3fIbs+ReGfaJxe5OTfoB2WHIp3tpZ6QdW4plDERwB6z7BMavSij48eWusYKeoLSLlAjIWMknATS3Y0itRVl5TdGVtS0SouX1ujsUBBqg6mMH2izVwYYbPQ8OenfkoWcgGjk=,iv:4y19bg4CuVqHXsnrpJh2ZF9gh2vSEQWQcC6Qni26gMg=,tag:LEdXsbMzbxmbpOnBSj2j2A==,type:str]
    shamir_threshold: 3
    version: 3.13.1
