apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:q+BzptZkXZAwntp8r9tUNNVKYn4FVoLxraI5q0fliI+uJR7PFvuVL1meJ4oESO6LBC7A3YQRfOJcFyisuqjh7hMuCFT79hBl+zG4M7aa2eG3M5rD+3zolQi4byoeIfDrIvhm1UMRrLdkLT6RJBN5xjeE1WOYSNp9CsfjPllX/gLsG9uFN9zs0yZ9PgXjQ5HQeZ0gHNYq1vL2S9ILryJjpWibM2fvcGKQRk72Ydvtki05xH/T/XBlOfubFp0VF2BGx5StWHyPEme+vj+al4IHgbziNN4YZzu1j3AUnn9oG8XcBU7cnQbG6e2sxriqBBQhjfLwAsfMP+zR53/UZZ6T6b3oHKloQGKmFXk/NM0wHt8JNBA64dHFYpMRaFy64DNx,iv:s2skxeikySjmnsgVUjcualCeG+0DHnYScBBQdZzG3ic=,tag:MVxvoHHgD0HKftehpsoRVA==,type:str]
    identity.pub: ENC[AES256_GCM,data:PVMr35XFZk3nMHIhU/ZEkcCIOl+9dJz1CMEVXKnNdHsjS1MonJNed9OSEk/p0GGGYzd4piCrFuJITJLuR9Px6LCEtvb9kPy3+pB/GUxgmxnolktvQGyaslGfy/imQzP+HSDFzwDY54o2J6JFc3TUy+MqydLXlJUPpmMvj9vZUe5lhFt38I8LGwZtJXefdIhCwFMZeHDAMMzMAn7+gmqBR3qvHflvflhwbaiMROlkB01xzy13aLeEeZCf3cBXFhK3esl4DhCLslGqimOhWw==,iv:7GHbo02fF/cBn3C+3NUjX2LhuHDkfZuVxkWWXwtt38I=,tag:SfyIqM1EdZ5KuxBagp3U7g==,type:str]
    known_hosts: ENC[AES256_GCM,data:du9SLWupd6W4yFePR9k39JoIQ0ThqTH5Jaav7+nwaBB+SN4NaZ0sgSwfiTQL1yUhJA6GQGQ0IBJHMouNrrSUQ4qV80lZXbyTSla0FDQSrtUZ0L2hlh4tq+M54/aewk2G7F/mpxV2WG+EYoeQUBCuqzzCMcHOd/eedbRoVDaOWIb8UuDn6GodvskqiJ/CooFRLWp0oVF320BpROwWrGWN0kP8S3c4/NU449Xl,iv:nmTI2kUj84iEH3uJCZ5Yp3iyeeIaKjjBAE4L1TevAKg=,tag:xbuUkGIJckju2nSEtItg0A==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZjZEU0RFd0d0Qkc1UnF1
            VDdWYklTY283UFQ2dkpwM1BpOWVZcTFCY3pvCjVjNDRJMlFBQkJQNHlpSEtETU5S
            bDZLOEVMK1lBUDdta3JKLzBBTTRnbHcKLS0tIEFUN3FzME83S1NFZXpNS2ROUnhB
            dWprbHRUNWNkandWL3JyMjh1WCtLeUEKgcOpd4xe/pVwGcn1/z7xlLPrzH7cxH88
            fcbvB2wQ/YjzWDaaopGPpsdFOVKvnREIG2ulTsJP3n8KNUNx1bhQSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9tnad5563zuz9mjnsypq2h93jhc03lmpehxat60wpczg0927prq7daz46
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-19T20:55:46Z"
    mac: ENC[AES256_GCM,data:fgUd5rFQymdYOtDXQbt1aiXIerN2HBFdKhdWdEt6HEPZ+C3nITYJkQYCPaeioTlfZnR5n2emR8oTb66DhyoXTkW2c8uq/jIVAm5d1INBjSL1tUqX4cinW6xJp4tOqo9VRLxgcJgiM74DKQkgkUXPJZOxle6TFft0OPjsDX9Tegw=,iv:66OHrBEOak+qXsqf8Ht78GKYxFdoJ+kcobhah9SAM7g=,tag:QIeA4IQ5RXSDDKIDK1yTDA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
