# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: paperless-oidc-secret
    namespace: paperless-ngx
type: Opaque
stringData:
    socialaccount_providers: ENC[AES256_GCM,data:krILMlvP1dj3e+k+sUF6hVHjlQyhFlWCXil4tJPOQDizKQRzNam4M4qDgI8AAneU+Yhe+u+r+ZDogudRfca1N+ilfvF7PkbuaEee7dLJPa29hKzVNdKSWik+xncrZv5eHwPP4sQtmvJwhbbr0dZPCHg5OBdNgIznPV5Omz6LU48a/8+NFKi1UUTiOFhwG55SKzmE/DoSqVZHIznX1uMeHA1P/iFiQ7kGwBXP33+zg796GtqBuCbBIYP68wamzJGzCgD7baBMHS6wX4jGCIBrJcNK9HcjxLubHkCaGN/zwwpIifSuUOzEoIK4o5MLsC/k4/B7YflQYE0Vws9ziNTe4KM+id5Euq67acIhtCiTDH3Gt+VogwijrXrdDS7w1stfGEbNDtUQVoQsX4ISF8H0PaIuYiRqMdYNzhcCHO7dJ5mXhjvt0KP6XJqEphtkC9ZQehnfS9jD+sVplz8uswyo/9z4ffkoll5Te7bscEM9xYMblscelRBd0hn972+iNCfXjA==,iv:xrdkVbt5s4t9ajf6ul3OOZJ/29YB39w2k/UKwonAFgs=,tag:IVCI0mwSWNiT4rAxcyPiMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMa1BvTXdtZ2RGL0syY3hw
            aCs2aGR1aXlvM2N4N0hTZnR1UmZ5T2dIdEFNCjBhdVF0ZFNaR3QxMEN4MkgvZkg0
            TDE3NnhKUWpsZGtUQzdQSU9FVUVDUFkKLS0tIEFsYjJDVys4VVJKaGwxbE1HdGNo
            V0NrTEIyTUNHd0x6aHpDaFBoakVSNG8KUx45aqazab+qXVro7Muz5cWdZdWAo9iD
            mixvCFXZcfOal8+VAqFnb8pz9JqwTtbrfwj7D06QASp++vXKuOibhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9tnad5563zuz9mjnsypq2h93jhc03lmpehxat60wpczg0927prq7daz46
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-19T23:14:43Z"
    mac: ENC[AES256_GCM,data:R4yE2BQ1IEsdlx5XmBymOeQ13gSJ4HOKinLMUgflKNfwjKkYEgLWTUgeElp8c3w9FINb4tO9NUrWK2hbqS3kdaEpsid8YlWJH5ESZBUeHcWCIGMmazAXuO7jMiloIVmvaaZ8YN46i5YhUNfs3zpD7ufEt0Jl90LuTPWe+R6Kny0=,iv:/Hskp8f6cV5lSiD4xTIUjZFY/OsbhE2eXj45aLsuUBc=,tag:s1P6zGJLzSl1VIzKhXRp4g==,type:str]
    shamir_threshold: 3
    version: 3.13.1
