# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: paperless-oidc-secret
    namespace: paperless-ngx
type: Opaque
stringData:
    socialaccount_providers: ENC[AES256_GCM,data:gJ6MzsAfM/ot4kTU9nSAqHjQTLMQJ2gx/7QyH/iRpvJWK/hIuwddJEhlO0U4ZTp6jxu/Ssw5NbwptPQjOGi12kqN+HHE6gEVNdyo1a6ih6zwsr3tJrIZh4v0LuMHBD3KraBqUQob35fD/Ru0nyNbVhn5x/36o5JXU503fJQdWWSj/v3g8RB9EcZxLtpBPf/wrJFSxTuFCwlhldkKdisJee+jJi2Bbp4sTEn89CPkBWkaFRacDEYsLhonJ2D1pQLG1V8Lb48a2Z7xrOc0kV3OrsLwNK5jBytLrYljoHyiLizKs9v4SjCwW3YrJmx0prROnKz9xFgndmu/ZaOQLdYTTkTvxU7wUaurX+RikRa+jf5pSgLof5pdTvc9wQFkL1yoI3K3Aqt1mwyegjahvTWIdwIKAztktSy/Hoc/733l36Hoj9OPjbrVnaypF85QqHqKgNFEVRBb+Ilre3LJVgNTNzjha/QvSstNbfe9QNQfgNS2OkE=,iv:S70kZW4UZSxmllu9shIjVvaaQ2W2dPPWQRVOtg9TFPU=,tag:AS8zJ/Weab6QMsyL1h583w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUmV5Y29pMGdrQkpRSGxi
            eFdQNmFNTWJLaVdpUFgyaGw2U3hONUhPWkNBCjFuWFpOMzVSa0o0Q3dJTS9UYXhu
            NERueWd4azJJT05UWldtS2p2TEE1UUUKLS0tIEZrcXozM2dNOFNkWHk5SjR5M2g5
            MXlXeS9GeSsrbmpoVUlzbm5kTDQrWkUKCwbiI5BoljNBDbh8BuUvgnGjVmIh/+s3
            mxOJnwu6Lg5PQCDh9SlIpLKVGLX8OZndSNd9aCHRc+2uldrljyerJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9tnad5563zuz9mjnsypq2h93jhc03lmpehxat60wpczg0927prq7daz46
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-19T22:59:35Z"
    mac: ENC[AES256_GCM,data:GZ52YQWG0KSkL22xDaiOt9iV1xX8O27OrQNzHDENuVvSSLP2Iye+WAyXDG+aVnj0owe4PVqlys7N2aMfsRmYAB61DQ7UzS0WgC7rlk6+tYjZi2OsQqdEm0h7xGSFGw41UPJIiVfO7TTlgzd4RJ78mk0rt50cx5AvJBovW9AOyY0=,iv:GiCluOeOj2eUR7PlaYRclK7omleiB/HiuZqbKT8F8RE=,tag:CbgVzIFgQ5KhASkfSLsPBw==,type:str]
    shamir_threshold: 3
    version: 3.13.1
