# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: paperless-oidc-secret
    namespace: paperless-ngx
type: Opaque
stringData:
    socialaccount_providers: ENC[AES256_GCM,data:8uTP2tE56/H57t+FvIHAbVp/8vtKblQ46BOreYrXt+wcoZniwmmvm4TFmuf84sosNew9yjNywRkqYnIZcSAwBkXgZX4IqWw5XQOJyB1pjBEDWcX6Ip27rhIVVcxjTBruu2xLWUUtCxyJHrgN9k8c1Rog0p/tj+Qfxg0i0YYTSIgg65t28+Dz4Eo4v11X9XUlgolJKVP+u5xN4csv6VYYtkoV0MjDB7ADC1ZDLeufdh/DCP9TqkX1y5FohLmt4RaqfNapLRq4yBPNDW7iaYLJMbPQ1eitpVTxK0K0tdOC7wrEstWS7StE+cfWZS4uho424TLphFp8oxD/tmhKdiDXCn9aN5FCS12elqTetRY2ZciAUOWQw2JBRfQ4kkOkRD4X37reMFmBvUHpalp9+70X7dL2u/8WJRMSuyPIzkqzPTkh0PUTQcdK33Uf4J5505bNHmqqzelW54Po2yarQEqAmOyW15MZGyYX/zVBdPdKgqNMSoe388B6dNmjroQ0OQfiSeRMY/a1KqhOw00RmabeDmEUZMG812PDT3gP9ZYFLyFU93bIKL1TmUCRd0D8bpO9FwDtdc3xt4OzrH7Sw2kcG36l6Tj0d8v/WrHVw5bQjSHyHNyNkTzlUpnm5tV4D5KYNTsUyhK7BWiY9NfO0tNjaffA4SqoLfTsxe2s3RaCUV7VWeCnC5iwFWtsRMQKYc9+s9H4xQ1IFcQvRjh4F/AhDx3WTx9qB0UB04unSmeTUgvu5NetopJVFX8oC+EN4i/4UXBdM+zMYhSef4r3IC5N8rP/9KLc2kBU2nF0Kkw4i3FEn+38yTZgh625UqzafV62yoM9tFGmUdhh39/wyOY6IkIl1La1Dt4MRyInf550Met9pHoebyJDKQ==,iv:G6YYuW2AoYtrdo+/6veYfEvpFuARA3P+bmBK1Igu+cg=,tag:3AaQPC2QuY9n+dUGUaYgiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaWZlUXpHNTdSN0ZNMTkv
            WW84UitjaVFuVmV0VDJVUm93ZGNuN3J1RFNFCnJhWUFoeDVEUkZJb0piSHdKcWky
            ZXZTUnZ2c1JORFRNa0YyWDVPTkFLd1UKLS0tIHMxWjZ0eStUb29zRktVcVpuRjRZ
            anhFdTNEWElMeENGTytGenBtemVTWHMKZMsj2NOX+njlweGSNAmkGa8jHUcYB8M5
            kVj9LXL8evsSrfpsSC0Oe3NYhtUdvFubmH1syYh3hc/fRJ76IE4iZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v9tnad5563zuz9mjnsypq2h93jhc03lmpehxat60wpczg0927prq7daz46
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-24T17:42:16Z"
    mac: ENC[AES256_GCM,data:pC2JJ7iu8avJ4sJD4vnIldPysxk6FdOXnsMMRQztNv5V+W5GXH6zOyIfxyuIjJOHt/r4g2fnAfdJfmdD3mIfi3LxCdHpycw9zScHZbmPQXMrQdS5LRUIFFGUBGEtGskHmxFm6m8R+DRMuXnXjeK+++qVrBfg+3rzGGQmJyE5wQU=,iv:haQm2XsNped2pzFOuV4xSTt953xdR2TbVjzHFzhsAl4=,tag:L+QKjSf+PXafsyutLcgV4w==,type:str]
    shamir_threshold: 3
    version: 3.13.1
