---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  interval: 15m
  chart:
    spec:
      chart: forgejo
      version: 17.2.0
      sourceRef:
        kind: HelmRepository
        name: forgejo
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    strategy:
      type: Recreate
    persistence:
      enabled: true
      size: 10Gi
    gitea:
      admin:
        existingSecret: forgejo-admin-secret
      config:
        server:
          DOMAIN: git.${DOMAIN_0}
          ROOT_URL: https://git.${DOMAIN_0}/
        database:
          DB_TYPE: sqlite3
        service:
          DISABLE_REGISTRATION: true
        mailer:
          ENABLED: true
          SMTP_ADDR: ${SCALEWAY_SERVER}
          SMTP_PORT: 465
          FROM: ${SCALEWAY_SENDER_EMAIL}
          USER: ${SCALEWAY_USERNAME}
          PASSWD: ${SCALEWAY_PASSWORD}
    ingress:
      enabled: true
      className: external
      annotations:
        cert-manager.io/cluster-issuer: domain-0-le-prod
      hosts:
        - host: git.${DOMAIN_0}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: forgejo-tls
          hosts:
            - git.${DOMAIN_0}
